### PR TITLE
removed tests and stories for App component

### LINKED ISSUE #17: Suggestion: Remove App component
I suggest we remove the App component since we have storybook. I can see how this is a place where we can "prove" that components are consumable, but we can achieve the same thing by sourcing our stories and tests from the `index.ts` file in each component.

If we don't remove `App` then I suggest we ignore it in coverage.

### PR DESCRIPTION
**Pull request by thispastwinter**
## Description

Removes App tests and story.

### 🔗 Reference

> _Relevant links (e.g. issue, design, etc.)_

- [LINK_NAME](LINK_URL)

### 📋 Acceptance Criteria

> _Checked off by PR **Assignees**_

- [ ] CRITERION_HERE

### 👩‍🔬 Test Instructions

> _Provided by PR **Assignees**_

1. TEST_STEP_HERE

## 🔎 Reviewer Checklist

> _Checked off by PR **Reviewers**_

- [ ] Merge destination is correct
- [ ] Code is correct as understood and conforms to quality standards
- [ ] Tests have been added where appropriate (unit, visual, end-to-end)
- [ ] Acceptance Criteria have been met

---

> ### Roles & Responsibilities
>
> #### 👨‍💻 Assignee
>
> - Initiator of this PR (be sure to set in GitHub UI)
> - Addresses feedback and change requests
> - Merges PR once approved (usually deletes branch unless `develop` or `release`)
>
> #### 👩‍💻 Reviewer
>
> - Invited to review PR by **Assignee** (via GitHub UI)
> - Is expected to complete a review and address followup

### CODE REVIEW

**Review by roblafeve — COMMENTED** [review]
Thanks for doing this! However, I think #17 is primarily suggesting that we remove `App` altogether—and if you do that, you might as well remove `./src/index.tsx` and if you do that, you might as well remove `react-scripts` altogether. But, this might be a good short-term solution. What do you think?

**Comment by thispastwinter** [comment]
> Thanks for doing this! However, I think #17 is primarily suggesting that we remove `App` altogether—and if you do that, you might as well remove `./src/index.tsx` and if you do that, you might as well remove `react-scripts` altogether. But, this might be a good short-term solution. What do you think?

Yes, this is my best case short-term solution, otherwise the latter would require a much heavier lift.

**Review by roblafeve — DISMISSED** [review]
Cool 👌

**Comment by belv2c** [comment]
@thispastwinter Thanks for making these changes! Since we deleted the App test and story files, can we also update the main repo's README.md and the App component's README.md? They still have `App.stories.tsx` and `App.test.tsx` listed under the directory structure.

**Comment by thispastwinter** [comment]
> @thispastwinter Thanks for making these changes! Since we deleted the App test and story files, can we also update the main repo's README.md and the App component's README.md? They still have `App.stories.tsx` and `App.test.tsx` listed under the directory structure.

Absolutely. I'll get those corrections made.

**Review by belv2c — APPROVED** [review]
👍

**Pull request merged**
